/*
 * Project Ambrose by Imjustchico
 * The characters database's statement ids, the most characters one account's list returns, and the connection type that prepares them.
 */

#ifndef AMBROSE_CHARACTERDATABASE_H
#define AMBROSE_CHARACTERDATABASE_H

#include "MySQLConnection.h"

enum CharacterDatabaseStatements : uint32
{
    CHAR_SEL_SERVER_TIME,
    CHAR_SEL_CHARACTERS_BY_ACCOUNT,
    CHAR_SEL_CHARACTER,
    CHAR_INS_CHARACTER,
    CHAR_INS_APPEARANCE,
    CHAR_UPD_SOFT_DELETE,
    CHAR_UPD_RESTORE,
    CHAR_SEL_DELETED,
    CHAR_UPD_SHOULD_RENAME,
    CHAR_DEL_CHARACTER,
    CHAR_DEL_DELETED_BEFORE,
    CHAR_SEL_COUNT_BY_ACCOUNT,
    CHAR_UPD_ONLINE,
    CHAR_SEL_MAX_GUID,
    CHAR_INS_ID_SEQUENCE,
    CHAR_SEL_SETTINGS,
    CHAR_REP_SETTING,
    CHAR_DEL_SETTING,
    CHAR_INS_SETTING_AUDIT,
    CHAR_SEL_SETTING_AUDIT,
    CHAR_SEL_CHARACTER_STATS,
    CHAR_REP_CHARACTER_STATS,
    CHAR_UPD_POSITION,
    CHAR_UPD_PLACE,
    CHAR_SEL_CHARACTER_SPELLS,
    CHAR_REP_CHARACTER_SPELL,
    CHAR_SEL_CHARACTER_INVENTORY,
    CHAR_INS_ITEM_INSTANCE,
    CHAR_INS_CHARACTER_INVENTORY,
    CHAR_DEL_ITEM_INSTANCE,
    CHAR_UPD_ITEM_LOCK,
    CHAR_SEL_MAX_ITEM_GUID,
    CHAR_SEL_CHARACTER_EQUIPMENT,
    CHAR_INS_CHARACTER_EQUIPMENT,
    CHAR_DEL_CHARACTER_EQUIPMENT,
    CHAR_DEL_CHARACTER_INVENTORY,
    CHAR_SEL_SOCIAL_FRIENDS,
    CHAR_SEL_SOCIAL_IGNORES,
    CHAR_SEL_SOCIAL_REQUESTS,
    CHAR_SEL_SOCIAL_REQUEST_EXISTS,
    CHAR_INS_SOCIAL_REQUEST,
    CHAR_DEL_SOCIAL_REQUEST,
    CHAR_INS_SOCIAL_FRIEND,
    CHAR_DEL_SOCIAL_FRIEND,
    CHAR_UPD_SOCIAL_BEST_FRIEND,
    CHAR_INS_SOCIAL_IGNORE,
    CHAR_DEL_SOCIAL_IGNORE,
    MAX_CHARACTERDATABASE_STATEMENTS
};

inline constexpr uint32 MaxCharactersListed = 256;

class CharacterDatabaseConnection : public MySQLConnection
{
public:
    using Statements = CharacterDatabaseStatements;

    using MySQLConnection::MySQLConnection;

protected:
    void DoPrepareStatements() override;
};

#endif
